### ISSUE TITLE
Fedora 37 Support

### ISSUE THREAD

**Issue by thwaller** [taw00/ipfs-rpm#1]
Do you really want to enable copr.fedorainfracloud.org/taw/ipfs? [y/N]: y
Error: It wasn't possible to enable this project.
Repository 'fedora-37-x86_64' does not exist in project 'taw/ipfs'.
Available repositories: 'fedora-36-x86_64', 'fedora-35-x86_64'

**Comment by taw00** [comment]
Built.

**Comment by taw00** [comment]
Closing.
